
export const supabaseUrl = 'https://uggoeltlslijoehgnoes.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZ29lbHRsc2xpam9laGdub2VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTg1MjU2NjQsImV4cCI6MjAzNDEwMTY2NH0.3uvR_PbFmN6fbZ9LSxPk5T87IZH2mgQEp0NySUZ7cCI';