
export const supabaseUrl = 'https://lvkcevoozumpwpbojkcx.supabase.co';
export const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2a2Nldm9venVtcHdwYm9qa2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDg3MzIsImV4cCI6MjA2MTM4NDczMn0.COcC7-lZJdBu4_Q0igXPmS9_pnFz3AZI5vCKNXzC7IM';