create table users
(
    id                uuid                                   not null
        primary key,
    created_at        timestamp with time zone default now() not null,
    name              text,
    image             text,
    bio               text,
    "StudentIdNumber" text,
    address           text,
    "phoneNumber"     text,
    password          text,
    gender            varchar(10),
    birthday          date,
    college           text,
    major             text,
    grade             varchar(20),
    email             varchar(255)
)


create table posts
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone default now() not null,
    body       text,
    file       text,
    "userId"   uuid
)


create table time_slots
(
    slot_id       serial
        primary key,
    slot_name     varchar(20) not null,
    start_time    time        not null,
    end_time      time        not null,
    display_order integer     not null
)


create table "postLikes"
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone default now() not null,
    "postId"   bigint,
    "userId"   uuid
)

create table notifications
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp with time zone default now() not null,
    title        text,
    "senderId"   uuid,
    "receiverId" uuid,
    data         text
)



create table courses
(
    course_id   uuid                     default gen_random_uuid() not null
        primary key,
    user_id     uuid                                               not null,
    course_name varchar(100)                                       not null,
    color       varchar(20)              default 'blue'::character varying,
    created_at  timestamp with time zone default now()             not null
)


create table course_items
(
    item_id       uuid                     default gen_random_uuid() not null
        primary key,
    user_id       uuid                                               not null,
    course_id     uuid                                               not null,
    day_of_week   integer                                            not null
        constraint course_items_day_of_week_check
            check ((day_of_week >= 1) AND (day_of_week <= 7)),
    start_slot    integer                                            not null,
    end_slot      integer                                            not null,
    location      varchar(100),
    teacher       varchar(50),
    week_start    integer                  default 1,
    week_end      integer                  default 20,
    weeks_pattern text,
    created_at    timestamp with time zone default now()             not null,
    updated_at    timestamp with time zone default now()             not null,
    constraint valid_slots
        check (start_slot <= end_slot)
)




create table comments
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone default now() not null,
    text       text,
    "userId"   uuid,
    "postId"   bigint
)

